var meses = [
	"Os Ayatollas",
	"Os Nazis",
	"Os Talibãs",
	"O Lóbi",
	"A Ditadura",
	"A Censura",
	"O 1984",
	"Fascistas",
	"O Triumfo dos Porcos",
	"O PREC",
	"A Pandemia",
	"O Holocausto",
];

var dias = [
	"Do Politicamente Correcto",
	"Do Feminismo",
	"Do Marxismo Cultural",
	"De Black Lives Matter",
	"Do Ambientalismo",
	"Da Alimentação Saudável",
	"Do Socialismo",
	"Do Comunismo",
	"Das Pessoas com mais melanina",
	"Dos Jovens",
	"Do Islão",
	"Dos Videojogos",
	"Das Drogas Leves",
	"Da Wokeness",
	"Da Cultura do Cancelamento",
	"Da China",
	"Da Banda Desenhada",
	"Dos Ciganos",
	"Do RSI",
	"Da TAP",
	"Dos Impostos",
	"Dos Ciclistas",
	"Dos Vegetarianos",
	"Dos Sindicatos",
	"Da Ideologia de Género",
	"De Cuba",
	"Dos Gays",
	"Das Pessoas Trans",
	"Da Venezuela",
	"Do Povo",
	"Das Redes Sociais",
];
